[build-system]
requires = ["setuptools", "wheel", "setuptools_scm[toml]", "cython", "numpy"]

# enable version inference
[tool.setuptools_scm]

[tool.cibuildwheel]
# Disable building PyPy wheels on all platforms
skip = "pp*"
